// promise is an object representing eventual completion
const promise = new Promise()


FileSystemDirectoryHandle;lkjfdsal;;length;;kjkfdsa;;;;;;;;;;;;;;lkj;length;lkj;lkj

asdfasdffsaj;lkj  
asdf ;lkjjasdf ;lkjasdf lkjasdf ;lkjasd asdf ;lkjasdf ;lkj asdf ;lkjasdf ;lkjasdf ;lkjasddf ;lkjasdf ;lkkjasdf ;lkjj  
asdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf; a       j     length

asdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjkasdf ;llkjjasdf ;lkjjasddf ;lkjasdf ;lllkjasdf ;lkjasdf ;;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkkjasdf ;lkj
asdf ;lkjasdf ;lllkjasdf ;lkjjasdf ;llllkjasdf ;lkjasdf ;lkjjasdf ;lkjasdf ;lkjjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ; lkjlkjlkj;lkj;lkj;;lkjjj;;lkj;lkj;lkj;lkjj;lkj;jlkj;lkj;ljkasdff ;lkjasdf ;lkjasdf ;lkjasdf ;lkasdf ;lkjasdf  ;;lkkjasdf ;lkjasdf ;lkkjasdf ;lkjasdf length;lkjasdf ;lkjasdf ;lkjjasdf;lkjasdf ;lkjasdf ;llkkasdf ;lkjkasdf ;llkjasdf ;lkjsaasdf ;lkjasdf ;lkjadasdf length;;llllkjasdf  ;lkjasdf ;lkjasdf ;lkjasdf ;lkjsasdf ;lkjasdf ;lkjasdf ;klkjasdf ;lkjasdf ;lkjsasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf length;;lkjasdf ;lkjasdf ;lkj asdf ;lkjad asdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkkjjasdf ;lkjasdf ;lkjasdf ;lkjasasdf ;lkjasdf ;lkjasdf ;lkjasdf ;jlkjasdf ;lllllkjasdf ;lkjasdf ;lkjasdf length;;lkkjasdf ;lkjassdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lklkjjasdf ;lkjasdf ;kllkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf  ;lkjasdf ;lkjasdf ;lkjasdf ;lkkkjlkasdf ;lkjasdf ;klkjasdf ;lkjasdf ;lkjasdf ;lkjsdf ;lkjasdf ;lkjasdf ;lkjasdf ;kljasdf ;lkjasdf ;lkjasdf ;lkjasdf ;llkjasdf ;lkjjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkkkjasdf ;lkkjasdf ;lkjasdf ;lkjasddf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasff ;lkjasdf ;lkljjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;klkjasdf ;lkjasdf ;lkkjasdf ;lkjassdf ;lkj ;asdf ;asdfgf';lkkkj glkkjasdf ;lkjasdf ;lkjasdf ;lkjasdf length;lkj aasdf ;lkkjasdf ;l;kjasdf ;lkjasdf ;lkkjjasdf ;ljassdf ;lkjasdf ; lkjasdf ;lkkjasdf ;lkjaaasdf ;lkjasd asdf ;lkjasdf ;lkjasdf ;lkjasd fasdf assdffasdfasdfasdfasdfasdfassdfasdf asdf asdf asdf asdf asdf ;lkjasdf ;lkjasdf ;lkjsasdf ;lkjasdf ;ljjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjassdf ;lkjasdf ;lkjasdf ;lkjasdf ;ljkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkkkjasdf ;lkjasdf  ;lkjasdf ;lkjsasdf ;lkjasdf ;lkjasdf ;lkjadsdf ; lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lasdf ;asdf ;lkjasdf  ;llkjasdf ;lkjsdf ;lkjasdf ;lkljlhkkkkkkkkkkkkkkkkkkkdsasdf ;lkjasdf ;lkjasdf ;lkjasdf ;lkjasdfg ;lkjhasddf ;lkjasddf ;lkjasdf ;lkj'asdf ;;lkjk';lkj